spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
  h2:
    console:
      enabled: true
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 713024994964-nv6vm5339tr2pi46lmkmub3th4ibqvph.apps.googleusercontent.com
            client-secret: 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
            scope:
              - email
              - profile
          github:
            client-id: 5c168df99aa8aa86725b
            client-secret: 49fd201a7c442fb35fe98ccd92205936d18791e6
jwt:
  issuer: ajufresh@gmail.com
  secret_key: study-springboot