server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/security_jwt
    username: limbaba
    password: 1234
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
        format_sql: true
        show_sql: true
        default_batch_fetch_size: 100
    open-in-view: false
  sql:
    init:
      mode: never

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 713024994964-nv6vm5339tr2pi46lmkmub3th4ibqvph.apps.googleusercontent.com
            client-secret: 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
            scope:
              - email
              - profile
          github:
            client-id: 5c168df99aa8aa86725b
            client-secret: 49fd201a7c442fb35fe98ccd92205936d18791e6
            scope:

jwt:
  issuer: ajufresh@gmail.com
  secret_key: study-springboot

## cors 설정
#cors:
#  allowed-origins: 'http://localhost:3000'
#  allowed-methods: GET,POST,PUT,DELETE,OPTIONS
#  allowed-headers: '*'
#  max-age: 3600
#
## 토큰 관련 secret Key 및 RedirectUri 설정
#app:
#  auth:
#    tokenSecret: 926D96C90030DD58429D2751AC1BDBBC
#    tokenExpiry: 1800000
#    refreshTokenExpiry: 604800000
#  oauth2:
#    authorizedRedirectUris:
#      - http://localhost:3000/oauth/redirect